/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.Curso;
import Negocio.NegocioCurso;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author diego
 */
public class MantenimientoCursos extends javax.swing.JInternalFrame {

    NegocioCurso negocioCurso;

    /**
     * ya tengo el boton agregar y la tabla falta: modificar y actualizar
     */
    public MantenimientoCursos() {
        initComponents();
        negocioCurso = new NegocioCurso();
        TableModel tableModel = this.fillTableModel();
        jTableCursoLista.setModel(tableModel);
        jTextAreaMensajes.setVisible(false);
    }

    private TableModel fillTableModel() {
        try {
            List<Curso> listProductos = negocioCurso.consultarTodosLosCursos(); //hacer negocio Curso y las utilidades y manejo de datos curso y la interface 

            Object[] columnas = new Object[]{"Nombre Curso", "laboratorio", "Cupo", "Costo", "Profesor 1 ", "Profesor 2", "ingenieria Sistemas", "ingenieria software"};
            Object[][] datos = new Object[listProductos.size()][columnas.length];
            for (int i = 0; i < listProductos.size(); i++) {
                datos[i][0] = listProductos.get(i).getNombreCurso();
                datos[i][1] = listProductos.get(i).isTipo();
                datos[i][2] = listProductos.get(i).getCupo();
                datos[i][3] = listProductos.get(i).getCosto();
                datos[i][4] = listProductos.get(i).getProfesor1();
                datos[i][5] = listProductos.get(i).getProfesor2();
                datos[i][6] = listProductos.get(i).isSistemas();
                datos[i][7] = listProductos.get(i).isSoftware();

            }
            DefaultTableModel model = new DefaultTableModel(datos, columnas);
            return model;

        } catch (Exception ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private boolean validarCurso() {
        boolean bandera = true;
        if (jTextFieldNombreCurso.getText().isEmpty()) {
            jTextAreaMensajes.setVisible(true);
            jTextAreaMensajes.setText("debe asignar un nombre al curso");
        }

        if (!isDouble(jTextFieldCostoCurso.getText()) || jTextFieldCostoCurso.getText().isEmpty()) {
            jTextAreaMensajes.setVisible(true);
            jTextAreaMensajes.setText("debe asignar un valor al curso en numeros");
        }

        if (jTextFieldProfesor1.getText().isEmpty()) {
            jTextAreaMensajes.setVisible(true);
            jTextAreaMensajes.setText("debe asignar un profesor al curso");
        }
        if (jCheckBoxLaboratorioCondicional.isSelected() == true && jTextFieldProfesor2.getText().isEmpty()) {
            jTextAreaMensajes.setVisible(true);
            jTextAreaMensajes.setText("por ser laboratorio debe asignar otro profesor al curso");

        }
        return bandera;
    }

    private boolean isDouble(String numero) {
        try {
            Double.parseDouble(numero);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void limpiarCampos() {
        jTextFieldNombreCurso.setText("");
        jTextFieldCostoCurso.setText("");
        jTextFieldProfesor1.setText("");
        jTextFieldProfesor2.setText("");
        jCheckBoxLaboratorioCondicional.isSelected();//revisar esto o ver si hay que cambiar la funcion para deseleccionar
        jCheckBoxSistemas.isSelected();
        jCheckBoxSoftware.isSelected();

    }

    private Curso capturaCurso() {
        Curso curso = new Curso();
        curso.setNombreCurso(jTextFieldNombreCurso.getText());
        curso.setCosto(Double.parseDouble(jTextFieldCostoCurso.getText()));
        curso.setCupo(Integer.parseInt(jLabelCupo.getText()));
        curso.setProfesor1(jTextFieldProfesor1.getText());
        curso.setProfesor2(jTextFieldProfesor2.getText()); //aqui puede dar un error logico
        curso.setTipo(jCheckBoxLaboratorioCondicional.isSelected());
        curso.setSistemas(jCheckBoxSistemas.isSelected());
        curso.setSoftware(jCheckBoxSoftware.isSelected());

        return curso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxLaboratorioCondicional = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabelCupo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCostoCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldProfesor1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldProfesor2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxSistemas = new javax.swing.JCheckBox();
        jCheckBoxSoftware = new javax.swing.JCheckBox();
        jButtonAgregarCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCursoLista = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButtonModificarCurso = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMensajes = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Administrador de cursos");

        jLabel1.setText("Nombre del curso");

        jCheckBoxLaboratorioCondicional.setText("Marque la casilla si este curso es laboratorio");
        jCheckBoxLaboratorioCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLaboratorioCondicionalActionPerformed(evt);
            }
        });

        jLabel3.setText("Cupo total");

        jLabelCupo.setText("20");

        jLabel5.setText("Costo del curso");

        jTextFieldCostoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostoCursoActionPerformed(evt);
            }
        });

        jLabel6.setText("Profesor asignado 1");

        jLabel7.setText("Profesor asignado 2");

        jLabel10.setText("Carrera");

        jCheckBoxSistemas.setText("Ingenieria sistemas");
        jCheckBoxSistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSistemasActionPerformed(evt);
            }
        });

        jCheckBoxSoftware.setText("Ingenieria del software");

        jButtonAgregarCurso.setText("Agregar Curso");
        jButtonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCursoActionPerformed(evt);
            }
        });

        jTableCursoLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "laboratorio", "Cupo", "Costo", "Profesor 1", "Profesor 2", "Ingenieria sistemas", "Ingenieria Software"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCursoLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCursoListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCursoLista);

        jButtonModificarCurso.setText("Actualizar");
        jButtonModificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCursoActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jTextAreaMensajes.setEditable(false);
        jTextAreaMensajes.setColumns(20);
        jTextAreaMensajes.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMensajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)
                        .addComponent(jCheckBoxSistemas)
                        .addGap(51, 51, 51)
                        .addComponent(jCheckBoxSoftware)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelCupo)
                                            .addComponent(jTextFieldProfesor1)
                                            .addComponent(jTextFieldProfesor2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCostoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxLaboratorioCondicional))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAgregarCurso)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377))))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButtonModificarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButtonEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxLaboratorioCondicional))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelCupo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCostoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldProfesor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldProfesor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBoxSistemas)
                    .addComponent(jCheckBoxSoftware))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarCurso)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarCurso)
                    .addComponent(jButtonEliminar))
                .addGap(53, 53, 53)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxLaboratorioCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLaboratorioCondicionalActionPerformed
        if (jCheckBoxLaboratorioCondicional.isSelected() == true) { //si el check de laboratorio esta seleccionado habilita el campo de segundo profesor
            jTextFieldProfesor2.setEnabled(true);
        } else {
            jTextFieldProfesor2.setEnabled(false);
        }

        if (jCheckBoxLaboratorioCondicional.isSelected() == true) { //si el check esta seleccionado ajusta el cupo a 15 estudiantes, sino a 20 estudiantes
            jLabelCupo.setText("15");
        } else {
            jLabelCupo.setText("20");

        }
    }//GEN-LAST:event_jCheckBoxLaboratorioCondicionalActionPerformed

    private void jTextFieldCostoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostoCursoActionPerformed

    private void jCheckBoxSistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSistemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSistemasActionPerformed

    private void jButtonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCursoActionPerformed

        if (validarCurso()) {
            try {
                negocioCurso.agregar(this.capturaCurso());
                jTextAreaMensajes.setText("curso ingresado con exito");

            } catch (Exception e) {
                jTextAreaMensajes.setText("ups ocurrio un error");
            }

        } else {
            jTextAreaMensajes.setVisible(true);
        }
        limpiarCampos();
    }//GEN-LAST:event_jButtonAgregarCursoActionPerformed

    private void jButtonModificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCursoActionPerformed

        try {
            negocioCurso.Actualizar(this.capturaCurso());
            jTextAreaMensajes.setText("curso actualizado con exito");

        } catch (Exception e) {
            jTextAreaMensajes.setText("ups ocurrio un error");
        }

        jTextAreaMensajes.setVisible(true);

        limpiarCampos();

    }//GEN-LAST:event_jButtonModificarCursoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        try {
            negocioCurso.eliminar(this.capturaCurso());
            jTextAreaMensajes.setText("curso eliminado con exito");

        } catch (Exception e) {
            jTextAreaMensajes.setText("ups ocurrio un error");
        }

        jTextAreaMensajes.setVisible(true);

        limpiarCampos();

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableCursoListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCursoListaMouseClicked
        int indice = jTableCursoLista.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel) jTableCursoLista.getModel();
        jTextFieldNombreCurso.setText(model.getValueAt(indice, 0).toString());
        jCheckBoxLaboratorioCondicional.setText(model.getValueAt(indice, 1).toString());   //revisar los checkbox     
        jTextFieldCostoCurso.setText(model.getValueAt(indice, 3).toString());
        jTextFieldProfesor1.setText(model.getValueAt(indice, 4).toString());
        jTextFieldProfesor2.setText(model.getValueAt(indice, 5).toString());
        jCheckBoxSistemas.setSelected(Boolean.parseBoolean((String) model.getValueAt(indice, 6)));
        jCheckBoxSoftware.setText(model.getValueAt(indice, 7).toString());
        
    }//GEN-LAST:event_jTableCursoListaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAgregarCurso;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificarCurso;
    private javax.swing.JCheckBox jCheckBoxLaboratorioCondicional;
    private javax.swing.JCheckBox jCheckBoxSistemas;
    private javax.swing.JCheckBox jCheckBoxSoftware;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCupo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableCursoLista;
    private javax.swing.JTextArea jTextAreaMensajes;
    private javax.swing.JTextField jTextFieldCostoCurso;
    private javax.swing.JTextField jTextFieldNombreCurso;
    private javax.swing.JTextField jTextFieldProfesor1;
    private javax.swing.JTextField jTextFieldProfesor2;
    // End of variables declaration//GEN-END:variables
}
