/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.util.Locale;

/**
 *
 * @author diego
 */
public class Universidad extends javax.swing.JFrame {

    MantenimientoCursos mantenimientoCursos;
    AdministradorEstudiantes administradorEstudiante;
    ModuloMatricula matriculaCursos;
    Sobre sobre;
    

    /**
     * Creates new form Matricula
     */
    public Universidad() {
        initComponents();
        mantenimientoCursos = new MantenimientoCursos();
        mantenimientoCursos.setVisible(false);
        desktopPane.add(mantenimientoCursos);
        
        administradorEstudiante = new AdministradorEstudiantes();
        administradorEstudiante.setVisible(false);
        desktopPane.add(administradorEstudiante);
        
        matriculaCursos = new ModuloMatricula();
        matriculaCursos.setVisible(false);
        
        sobre = new Sobre();
        sobre.setVisible(false);
        desktopPane.add(sobre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        MenuAdministrativo = new javax.swing.JMenu();
        CursosMenuItem = new javax.swing.JMenuItem();
        EstudiantesMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemMatricula = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        MenuAdministrativo.setMnemonic('e');
        MenuAdministrativo.setText("Administrativos");

        CursosMenuItem.setMnemonic('t');
        CursosMenuItem.setText("Administrador cursos");
        CursosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosMenuItemActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(CursosMenuItem);

        EstudiantesMenuItem.setMnemonic('y');
        EstudiantesMenuItem.setText("Administrador de estudiantes");
        EstudiantesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiantesMenuItemActionPerformed(evt);
            }
        });
        MenuAdministrativo.add(EstudiantesMenuItem);

        menuBar.add(MenuAdministrativo);

        jMenu4.setText("Estudiantes");

        jMenuItemMatricula.setText("Matricula estudiantes");
        jMenuItemMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatriculaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemMatricula);

        menuBar.add(jMenu4);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Sobre");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Informacion");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void CursosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosMenuItemActionPerformed
        
        mantenimientoCursos.setVisible(true);
    }//GEN-LAST:event_CursosMenuItemActionPerformed

    private void EstudiantesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiantesMenuItemActionPerformed
        
        administradorEstudiante.setVisible(true);
    }//GEN-LAST:event_EstudiantesMenuItemActionPerformed

    private void jMenuItemMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatriculaActionPerformed
       matriculaCursos.setVisible(true);
    }//GEN-LAST:event_jMenuItemMatriculaActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        sobre.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Universidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CursosMenuItem;
    private javax.swing.JMenuItem EstudiantesMenuItem;
    private javax.swing.JMenu MenuAdministrativo;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemMatricula;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
